# Generated by Django 6.0.2 on 2026-03-15 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capacity_type', models.CharField(choices=[('general', 'General admission'), ('reserved', 'Reserved seating')], default='reserved', max_length=20)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='venues.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='venues.hall')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('hall', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('row_prefix', models.CharField(blank=True, max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='venues.zone')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('zone', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_label', models.CharField(max_length=20)),
                ('seat_number', models.CharField(max_length=20)),
                ('pos_x', models.DecimalField(blank=True, decimal_places=2, help_text='X for seat map', max_digits=8, null=True)),
                ('pos_y', models.DecimalField(blank=True, decimal_places=2, help_text='Y for seat map', max_digits=8, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='venues.hall')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='venues.section')),
            ],
            options={
                'ordering': ['sort_order', 'row_label', 'seat_number'],
                'unique_together': {('hall', 'row_label', 'seat_number')},
            },
        ),
    ]
