# Generated by Django 6.0.2 on 2026-04-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
