# Generated by Django 6.0.2 on 2026-04-04 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_hall_layout_json'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hall',
            options={'verbose_name': 'سالن', 'verbose_name_plural': 'سالن\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['sort_order', 'row_label', 'seat_number'], 'verbose_name': 'صندلی', 'verbose_name_plural': 'صندلی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'بخش صندلی', 'verbose_name_plural': 'بخش\u200cهای صندلی'},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'verbose_name': 'مکان برگزاری', 'verbose_name_plural': 'مکان\u200cهای برگزاری'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'ناحیه سالن', 'verbose_name_plural': 'نواحی سالن'},
        ),
        migrations.AlterField(
            model_name='hall',
            name='capacity_type',
            field=models.CharField(choices=[('general', 'ورود آزاد'), ('reserved', 'صندلی\u200cدار')], default='reserved', max_length=20, verbose_name='نوع ظرفیت'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='layout_json',
            field=models.JSONField(blank=True, default=dict, help_text='خروجی ویرایشگر چیدمان در ادمین؛ همراه با رکوردهای صندلی و EventSeat برای نمایش و فروش استفاده می\u200cشود.', verbose_name='چیدمان صندلی (JSON)'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(help_text='نام سالن داخل همان مکان (مثلاً سالن اصلی، سالن شماره ۲).', max_length=200, verbose_name='نام سالن'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='venues.venue', verbose_name='مکان'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='venues.hall', verbose_name='سالن'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='pos_x',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='در صورت نبود layout_json برای نقشه استفاده می\u200cشود.', max_digits=8, null=True, verbose_name='موقعیت X'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='pos_y',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='در صورت نبود layout_json برای نقشه استفاده می\u200cشود.', max_digits=8, null=True, verbose_name='موقعیت Y'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row_label',
            field=models.CharField(max_length=20, verbose_name='برچسب ردیف'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(max_length=20, verbose_name='شماره صندلی'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='venues.section', verbose_name='بخش'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام بخش'),
        ),
        migrations.AlterField(
            model_name='section',
            name='row_prefix',
            field=models.CharField(blank=True, max_length=20, verbose_name='پیشوند ردیف'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='section',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='venues.zone', verbose_name='ناحیه'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.TextField(blank=True, help_text='آدرس پستی کامل یا توضیح مسیر. برای فیلتر «کجا» از شهر و محله استفاده کنید.', verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='area',
            field=models.CharField(blank=True, help_text='مثلاً ونک یا منطقه ۳؛ اختیاری.', max_length=100, verbose_name='محله / منطقه'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(blank=True, help_text='مثلاً تهران؛ برای فیلتر مکان در سایت.', max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(help_text='نام نمایشی برای مخاطب و لیست رویدادها (مثلاً تالار وحدت). این فیلد عنوان مکان است، نه آدرس کامل.', max_length=200, verbose_name='نام مکان'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='timezone',
            field=models.CharField(default='Asia/Tehran', max_length=50, verbose_name='منطقهٔ زمانی'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='venues.hall', verbose_name='سالن'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام ناحیه'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب'),
        ),
    ]
