# Generated by Django 5.2.15 on 2026-06-22 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_remove_zone_section_grid_seatmap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['sort_order', 'grid_r', 'grid_c', 'row_label', 'seat_number'], 'verbose_name': 'صندلی', 'verbose_name_plural': 'صندلی\u200cها'},
        ),
        migrations.AlterField(
            model_name='hall',
            name='layout_json',
            field=models.JSONField(blank=True, default=dict, help_text='نسخه ۲؛ ذخیره با فرم سالن و همگام با جدول صندلی\u200cها.', verbose_name='ویرایشگر نقشه (JSON)'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='venues.hall', verbose_name='سالن'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seat',
            name='row_label',
            field=models.CharField(max_length=20, verbose_name='ردیف'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(max_length=20, verbose_name='شماره'),
        ),
    ]
