# Generated by Django 5.2.15 on 2026-06-22 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0006_alter_seat_options_alter_hall_layout_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('sale_starts_at', models.DateTimeField(blank=True, null=True)),
                ('sale_ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_reserved_seating', models.BooleanField(default=False)),
                ('organizer', models.CharField(blank=True, max_length=200)),
                ('purchase_notes', models.TextField(blank=True, help_text='هر خط یک نکته در صفحهٔ خرید نمایش داده می\u200cشود.', verbose_name='نکات خرید')),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='venues.hall')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='venues.venue')),
            ],
            options={
                'verbose_name': 'رویداد',
                'verbose_name_plural': 'رویدادها',
            },
        ),
        migrations.CreateModel(
            name='EventRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_key', models.CharField(blank=True, max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='events.event')),
            ],
            options={
                'verbose_name': 'امتیاز رویداد',
                'verbose_name_plural': 'امتیازهای رویداد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('standing_total', models.PositiveIntegerField(default=0, help_text='بلیت بیرون از ظرفیت (صفر = غیرفعال).', verbose_name='ظرفیت ایستاده')),
                ('standing_available', models.PositiveIntegerField(default=0, verbose_name='مانده ایستاده')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='events.event')),
            ],
            options={
                'verbose_name': 'سانس',
                'verbose_name_plural': 'سانس\u200cها',
                'ordering': ['starts_at', 'id'],
            },
        ),
    ]
