from django.db import migrations, models
import django.db.models.deletion


def ensure_eventrowprice_table(apps, schema_editor):
    connection = schema_editor.connection
    existing = set(connection.introspection.table_names())
    with connection.cursor() as cursor:
        if "tickets_eventrowprice" not in existing:
            cursor.execute(
                """
                CREATE TABLE tickets_eventrowprice (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    row_label varchar(20) NOT NULL,
                    price numeric(12, 0) NOT NULL,
                    event_id integer NOT NULL
                        REFERENCES events_event(id) ON DELETE CASCADE
                        DEFERRABLE INITIALLY DEFERRED,
                    CONSTRAINT tickets_eventrowprice_event_id_row_label_uniq
                        UNIQUE (event_id, row_label)
                );
                """
            )
            return

        cursor.execute(
            """
            ALTER TABLE tickets_eventrowprice
            DROP CONSTRAINT IF EXISTS tickets_eventrowprice_event_id_7ff3eaf9_fk;
            """
        )
        cursor.execute(
            """
            ALTER TABLE tickets_eventrowprice
            ADD CONSTRAINT tickets_eventrowprice_event_id_7ff3eaf9_fk
            FOREIGN KEY (event_id) REFERENCES events_event(id)
            ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="EventRowPrice",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "row_label",
                            models.CharField(max_length=20, verbose_name="ردیف"),
                        ),
                        (
                            "price",
                            models.DecimalField(
                                decimal_places=0,
                                max_digits=12,
                                verbose_name="قیمت",
                            ),
                        ),
                        (
                            "event",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="row_prices",
                                to="events.event",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "قیمت ردیف",
                        "verbose_name_plural": "قیمت\u200cهای ردیف",
                        "unique_together": {("event", "row_label")},
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    ensure_eventrowprice_table, migrations.RunPython.noop
                ),
            ],
        ),
    ]
